---
# Dataset options
data:         [/home/barun/Projects/blocks/data/simdata/blocks_data_v2/]
batch-size:   16
num-workers:  8
train-per:    0.6
val-per:      0.15
step-len:     2
seq-len:      1
ctrl-type:    actdiffvel
gripper-ctrl-type: vel
robot:        yumi
use-failures: True
da-threshold: 0.01
da-winsize:   5

# Model options
no-batch-norm:      False
nonlin:             prelu
se3-type:           se3aa
num-se3:            8
init-transse3-iden: True
init-posese3-iden:  True
wide-model:         True
use-jt-angles:		  True

# Mask options
use-wt-sharpening: True
sharpen-start-iter: 0
sharpen-rate: 1.0

# Loss options
loss-type:        normmsesqrt
motion-norm-loss: True
pt-wt:            1.0
consis-wt:        10.0
loss-scale:       10000.0

# Mask consistency loss options
mask-consis-loss-type: kl
mask-consis-wt: 0.01
pre-mask-consis: True
use-se3nn: True

# Training options
no-cuda:        False
epochs:         20
start-epoch:    0
train-ipe:      5000
val-ipe:        2000
evaluate:       False
seed:           100

# Optimization options
optimization: rmsprop
lr:           1e-4
momentum:     0
weight-decay: 1e-4
lr-decay:     0.1
decay-epochs: 15

# Display/Save options
disp-freq: 50
save-dir:  trained_nets/blocks/simdata/1step/def_premask_kl_rmsprop
disp-err-per-mask: False
