---
# Dataset options
data:         [/home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_183851/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_203124/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_214259/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_230213/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-12_190929/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-12_201115/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-13_225254/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-14_03315/]
batch-size:   16
num-workers:  8
train-per:    0.7
val-per:      0.1
img-scale:    1e-3
img-suffix:	  None
step-len:     2
seq-len:      5
ctrl-type:    actdiffvel
mean-dt:		  0.0673 
std-dt:		  0.0020 
da-winsize:   5
da-threshold: 0.015
use-only-da-for-flows: False
reject-left-motion: True
reject-right-still: True

# Model options
no-batch-norm:      False
pre-conv:           False
nonlin:             prelu
init-flow-iden:	  True
wide-model:         True
use-jt-angles:		  False
use-full-jt-angles: False

# Loss options
loss-type:        normmsesqrt
motion-norm-loss: True
pt-wt:            1.0
loss-scale:       10000.0

# Training options
no-cuda:        False
use-pin-memory: False
epochs:         40
start-epoch:    0
train-ipe:      2500
val-ipe:        500
evaluate:       False
seed:           100

# Optimization options
optimization: adam
lr:           1e-4
momentum:     0
lr-decay:     0.1
decay-epochs: 50

# Display/Save options
disp-freq: 50
save-dir:  trained_nets/realdata/flow/5seq_normmsesqrt_motionnormloss
disp-err-per-mask: False
