---
# Dataset options
data:         [/home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_183851/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_203124/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_214259/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_230213/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-12_190929/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-12_201115/]
batch-size:   16
num-workers:  8
train-per:    0.7
val-per:      0.1
img-scale:    1e-3
img-suffix:	  None
step-len:     2
seq-len:      1
ctrl-type:    actdiffvel
mean-dt:		  0.0673 
std-dt:		  0.0020 
da-winsize:   5
da-threshold: 0.015
use-only-da-for-flows: False
reject-left-motion: True
reject-right-still: True

# Model options
no-batch-norm:      False
pre-conv:           False
nonlin:             prelu
se3-type:           se3aa
pred-pivot:         False
num-se3:            8
init-transse3-iden: True
init-posese3-iden:  True
#decomp-model:       False
local-delta-se3:    False
use-ntfm-delta:     False
wide-model:         True
use-gt-poses:		  False
use-gt-masks:		  False
use-jt-angles:		  False
use-jt-angles-trans: False

# Mask options
use-wt-sharpening: True
sharpen-start-iter: 0
sharpen-rate: 2.0
use-sigmoid-mask:  False

# Loss options
loss-type:        normmsesqrt
motion-norm-loss: True
fwd-pt-wt:        1.0
bwd-pt-wt:        1.0
fwd-consis-wt:    10.0
bwd-consis-wt:    10.0
fwd-normal-wt:		0.0
bwd-normal-wt:		0.0
normal-max-depth-diff: 0.05
bilateral-depth-smoothing: False
bilateral-window-width: 7
bilateral-depth-std:	0.005
fwd-poseanchor-wt: 0.0
bwd-poseanchor-wt: 0.0
pose-anchor-maskbprop: True
pose-anchor-grad-clip: 0.2
loss-scale:       10000.0

# Pivot options
delta-pivot: None

# Training options
no-cuda:        False
use-pin-memory: False
epochs:         20
start-epoch:    0
train-ipe:      5000
val-ipe:        2500
evaluate:       False
seed:           100

# Optimization options
optimization: adam
lr:           1e-4
weight-decay: 1e-4
lr-decay:     0.1
decay-epochs: 10
min-lr:		  1e-5

# Display/Save options
disp-freq: 50
save-dir:  trained_nets/realdata/fwdbwd/def_fwdbwd_pt1_consis10
disp-err-per-mask: False
