---
# Dataset options
data:         [/home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-2_182257/]
batch-size:   32
num-workers:  8
train-per:    0.7
val-per:      0.1
img-scale:    1e-3
img-suffix:	  None
step-len:     2
seq-len:      1
ctrl-type:    actdiffvel

# Model options
no-batch-norm:      False
pre-conv:           False
nonlin:             prelu
se3-type:           se3aa
pred-pivot:         False
num-se3:            8
init-transse3-iden: True
init-posese3-iden:  True
#decomp-model:       False
local-delta-se3:    False
use-ntfm-delta:     False
wide-model:         True
use-gt-poses:		  False
use-gt-masks:		  False

# Mask options
use-wt-sharpening: False
sharpen-start-iter: 0
sharpen-rate: 1.0
use-sigmoid-mask:  False

# Loss options
loss-type:        mse
motion-norm-loss: False
#delta-flow-loss:  False
fwd-wt:           1.0
bwd-wt:           1.0
consis-wt:        0.1
pose-dissim-wt:   0.001
delta-dissim-wt:  0.001
loss-scale:       10000.0

# Training options
no-cuda:        False
use-pin-memory: False
epochs:         50
start-epoch:    0
train-ipe:      2000
val-ipe:        500
evaluate:       False
seed:           100

# Optimization options
optimization: adam
lr:           1e-4
momentum:     0
lr-decay:     0.1
decay-epochs: 50

# Display/Save options
disp-freq: 25
save-dir:  trained_nets/realdata/dissim/8se3_soft_1seq_mse
disp-err-per-mask: False
