---
# Dataset options
data:         [/home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_183851/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_203124/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_214259/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-11_230213/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-12_190929/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-12_201115/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-14_154517/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2017-9-14_174138/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2018-2-2_190536_jt4_0to0.5/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2018-2-2_205941_jt5_0to0.25/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2018-2-2_221258_jt5_0.25to0.5/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2018-2-4_163504_jt5_0.5to0.75/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2018-2-4_173809_jt4_0.5to0.75/, /home/barun/Projects/rgbd/ros-pkg-irs/wamTeach/ros_pkgs/catkin_ws/src/baxter_motion_simulator/realdata/session_2018-2-8_162013_jt4_largevel/]
batch-size:   16
num-workers:  8
train-per:    0.8
val-per:      0.1
img-scale:    1e-3
img-suffix:	  None
step-len:     2
seq-len:      1
ctrl-type:    actdiffvel
mean-dt:		  0.0673 
std-dt:		    0.0020
da-winsize:   5
da-threshold: 0.015
use-only-da-for-flows: False
reject-left-motion: True
reject-right-still: True
use-xyzrgb: True

# Model options
no-batch-norm:      False
nonlin:             prelu
se3-type:           se3aa
num-se3:            8
init-transse3-iden: True
init-posese3-iden:  True
wide-model:         True
use-gt-poses:		  False
use-gt-masks:		  False
use-jt-angles:		  False
use-jt-angles-trans: False

# Mask options
use-wt-sharpening: True
sharpen-start-iter: 0
sharpen-rate: 1.0

# Loss options
loss-type:        normmsesqrt
motion-norm-loss: True
pt-wt:            1.0
consis-wt:        10.0
loss-scale:       10000.0

# Mask consistency loss options
mask-consis-loss-type: mse
mask-consis-wt: 1.0

# Training options
no-cuda:        False
use-pin-memory: False
epochs:         20
start-epoch:    0
train-ipe:      5000
val-ipe:        2000
evaluate:       False
seed:           100

# Optimization options
optimization: rmsprop
lr:           1e-4
momentum:     0
weight-decay: 1e-4
lr-decay:     0.1
decay-epochs: 15

# Display/Save options
disp-freq: 50
save-dir:  trained_nets/maskconsis/realdata/def_mse_wt1.0_rmsprop
disp-err-per-mask: False
